#' Unit tests for sparseGenSetCal.
#'
#' The tests that matter most are the cross-language ones: the R package is a
#' port of the Python reference implementation, so it has to reproduce the same
#' numbers on the same matrix rather than merely produce plausible ones.  The
#' fixtures for those live in tests/testthat/fixtures/ and are generated by
#' tests/testthat/make_fixtures.py.

fixture <- function(name) {
    path <- test_path("fixtures", name)
    if (!file.exists(path)) {
        skip(paste("fixture", name, "not present"))
    }
    path
}

small <- function(n_cells = 300, n_genes = 900, seed = 11) {
    make_synthetic_matrix(n_cells = n_cells, n_genes = n_genes, seed = seed)
}

# ----------------------------------------------------------------------
# the closed form
# ----------------------------------------------------------------------
test_that("tau falls as cells get deeper and is zero at the ceiling", {
    tau <- tie_break_level(c(100, 200, 400, 800, 1000), 1000, 20000)
    expect_true(all(diff(tau) < 0))
    expect_equal(tau[5], 0)
})

test_that("tie-break inclusion is the fraction of unused slots", {
    # 400 detected of 20,000, ceiling 1,000: 600 slots out of 19,600 genes.
    expect_equal(tie_break_inclusion(400, 1000, 20000), 600 / 19600)
    expect_equal(tie_break_inclusion(1000, 1000, 20000), 0)
    expect_equal(tie_break_inclusion(1200, 1000, 20000), 0)
})

test_that("tie_break_share is zero for an always-detected set and rises as it sparsifies", {
    depth <- rep(400, 500)
    expect_equal(tie_break_share(rep(1, 30), depth, 1000, 20000), 0)
    shares <- vapply(c(0.5, 0.1, 0.01), function(p) {
        tie_break_share(rep(p, 30), depth, 1000, 20000)
    }, numeric(1))
    expect_true(all(diff(shares) > 0))
    expect_gt(shares[3], 0.7)
})

test_that("counts are not multiplied as integers", {
    # sum() on a logical returns an integer, so a product of two margins
    # overflows to NA for any table of more than 46,341 cells -- and silently,
    # since NA is what an undefined statistic looks like anyway.  These tables
    # are deliberately larger than that and deliberately unbalanced, so an
    # association is present and a zero would be a failure rather than a null.
    n <- 40000
    groups <- c(rep(FALSE, n), rep(TRUE, n))
    outcome <- c(rep(TRUE, 0.6 * n), rep(FALSE, 0.4 * n),
                 rep(TRUE, 0.4 * n), rep(FALSE, 0.6 * n))
    stat <- sparseGenSetCal:::chi2_split(outcome, groups)
    expect_true(is.finite(stat))
    expect_gt(stat, 0)
    # and the same guard on the AUC, whose denominator is a product of two
    # counts: 40000 x 40000 is past 2^31 twice over
    score <- as.numeric(groups) + seq_along(groups) / length(groups)
    expect_true(is.finite(auroc(score, outcome)))
})

test_that("a perfectly separating score returns 1 and does not fail", {
    # The other end of the range: a score that separates the outcome
    # completely.  It is a legitimate value rather than a degenerate one, so
    # the framework reports it instead of clipping at 0.99 or refusing the
    # comparison -- an analysis whose gene set does separate has to be able to
    # say so.
    score <- c(seq_len(50), -seq_len(50))
    outcome <- c(rep(TRUE, 50), rep(FALSE, 50))
    expect_equal(auroc(score, outcome), 1)
    expect_equal(auroc(-score, outcome), 0)
    expect_true(is.finite(auroc(score, outcome)))
    # Heavy ties across the classes fall back on the mid-rank convention and
    # stay inside the unit interval rather than drifting past it.
    tied <- c(rep(1, 10), rep(0, 10))
    outcome <- c(rep(TRUE, 5), rep(FALSE, 5), rep(TRUE, 5), rep(FALSE, 5))
    expect_equal(auroc(tied, outcome), 0.5)
})

test_that("the outcome-driven cutpoint is found on a realistically sized table", {
    # Regression: the best cutpoint used to come back NA once the sample passed
    # a few hundred cells per side, which reports as "no outcome-driven rule"
    # rather than as an error, and would have flattered the very rule the
    # package exists to criticise.
    set.seed(3)
    score <- stats::rnorm(2000)
    outcome <- score + stats::rnorm(2000) > 0
    cut <- optimum_cutpoint(score, outcome)
    expect_true(is.finite(cut))
    expect_true(cut > stats::quantile(score, 0.05) &&
                cut < stats::quantile(score, 0.95))
})

test_that("the decomposition reproduces aucell exactly", {
    X <- small()
    cache <- rank_cache(X$matrix, X$genes, ceiling = 40)
    gs <- X$genes[1:8]
    # The ceiling is given to both calls.  Left out, each falls back to its own
    # default of ceil(0.05 * G), which for 900 genes is 45 -- not the cache's 40
    # -- and the two halves of equation (2) are then computed over different
    # windows of the ranking and silently disagree.
    split <- score_decomposition(cache, gs, X$matrix > 0, max_rank = 40)
    expect_equal(split$total, aucell(cache, gs, max_rank = 40), tolerance = 1e-12)
    expect_true(all(split$tie_break >= 0))
    expect_true(all(split$detected >= 0))

    # The defaults agree with each other, which is the property that lets a
    # caller omit the argument from both.  They agree even when the cache's
    # ceiling is lower than the default, because both read the same truncated
    # cache: the agreement is between the two functions, not with the truth --
    # and aucell() warns that what it returns is then a lower bound.
    expect_gt(ceiling(0.05 * cache$n_genes_total), cache$ceiling)
    expect_warning(default_aucell <- aucell(cache, gs),
                   "above the cache ceiling")
    expect_equal(score_decomposition(cache, gs, X$matrix > 0)$total,
                 default_aucell, tolerance = 1e-12)
})

test_that("preflight needs no score and returns a verdict", {
    set.seed(1)
    depth <- round(exp(rnorm(500, log(450), 0.4)))
    axis <- rnorm(500)
    pf <- preflight(depth, axis, 1000, 20000)
    expect_true(pf$verdict %in% c("CLEAR", "CAUTION", "CONFOUNDED"))
    expect_true(is.finite(pf$chance_band))
    # tau is a deterministic function of depth, so the confound has to be
    # strongest against an axis that tracks depth.
    axis2 <- depth + rnorm(500)
    pf2 <- preflight(depth, axis2, 1000, 20000)
    expect_gt(abs(pf2$tau_axis_rho), abs(pf$tau_axis_rho))
})

# ----------------------------------------------------------------------
# the rank cache
# ----------------------------------------------------------------------
test_that("every cell's ranks are a permutation of 1..ceiling", {
    X <- small(n_cells = 60)
    cache <- rank_cache(X$matrix, X$genes, ceiling = 20)
    # apply() would return a 20 x n_cells matrix here, so the assertion is made
    # per row rather than over the elements of that matrix.
    complete <- apply(cache$clipped, 1L, function(r) {
        identical(as.integer(sort(r[r > 0])), as.integer(seq_len(20)))
    })
    expect_true(all(complete))
})

test_that("the cache records each cell's depth over the whole panel", {
    X <- small(n_cells = 80)
    cache <- rank_cache(X$matrix, X$genes, ceiling = 20)
    expect_equal(cache$depth, as.integer(Matrix::rowSums(X$matrix > 0)))
    expect_equal(cache$n_genes_total, ncol(X$matrix))
})

test_that("the cache is reproducible under one seed and not under another", {
    X <- small(n_cells = 60)
    a <- rank_cache(X$matrix, X$genes, ceiling = 20, seed = 1)
    b <- rank_cache(X$matrix, X$genes, ceiling = 20, seed = 1)
    c_ <- rank_cache(X$matrix, X$genes, ceiling = 20, seed = 2)
    expect_identical(a$clipped, b$clipped)
    expect_false(identical(a$clipped, c_$clipped))
})

test_that("a cache refuses a ceiling the matrix cannot support", {
    X <- small()
    expect_error(rank_cache(X$matrix, X$genes, ceiling = ncol(X$matrix)),
                 "ceiling must lie in")
})

# ----------------------------------------------------------------------
# matched nulls
# ----------------------------------------------------------------------
test_that("a matched null never reuses a gene of the set it replaces", {
    # This is a regression test.  Excluding only the gene being replaced leaves
    # the set's other members eligible; the drawn set then shares genes with the
    # observation, and every P value drawn from it is conservative.
    X <- small(n_cells = 300, n_genes = 900, seed = 21)
    cache <- rank_cache(X$matrix, X$genes, ceiling = 40)
    builder <- MatchedNullBuilder$new(cache, det_floor = 0.005, seed = 5)
    gs <- cache$genes[seq_len(8)]
    sets <- builder$sample(gs, 20, kind = "expression")
    overlaps <- vapply(sets, function(s) length(intersect(s, gs)), integer(1))
    expect_equal(sum(overlaps), 0)
})

test_that("the drawn sets match the observed detection rate", {
    X <- small(n_cells = 300, n_genes = 900, seed = 22)
    cache <- rank_cache(X$matrix, X$genes, ceiling = 40)
    # Genes of middling detection: the sparsest decile is censored by the
    # detection floor, which is what the next test covers.
    middle <- order(abs(cache$detection - stats::median(cache$detection)))
    gs <- cache$genes[middle][seq_len(10)]
    built <- construct_expression_matched_null(cache, gs, n_sets = 5, seed = 2)
    expect_lt(abs(built$detection_ratio - 1), 0.05)
    expect_equal(built$max_overlap, 0L)
    expect_equal(built$status, "PASS")
})

test_that("the null status does not depend on how many draws were asked for", {
    # The status is a property of the pool, not of the sample size.  Deciding
    # it on the largest gap over draws made it a function of n_sets instead: a
    # maximum can only grow as more draws are taken, so one pool would pass at
    # 25 draws and fail at 100.
    X <- small(n_cells = 400, n_genes = 1200, seed = 31)
    cache <- rank_cache(X$matrix, X$genes, ceiling = 50)
    band <- which(cache$detection > 0.01 & cache$detection < 0.08)
    expect_gte(length(band), 12)
    gs <- cache$genes[band][seq_len(12)]

    statuses <- character(0)
    worsts <- numeric(0)
    means <- numeric(0)
    for (n in c(10, 50, 200)) {
        built <- construct_expression_matched_null(cache, gs, n_sets = n,
                                                   seed = 11)
        expect_equal(built$max_overlap, 0L)
        statuses <- c(statuses, built$status)
        worsts <- c(worsts, built$worst_detection_gap)
        means <- c(means, built$mean_detection_gap)
    }
    expect_length(unique(statuses), 1)
    # The maximum is monotone in the draw count -- which is the reason it
    # cannot decide the status -- while the mean settles down.
    expect_lte(worsts[1], worsts[3] + 1e-9)
    expect_lt(max(means) - min(means), 0.01)
    expect_true(all(worsts >= means))
})

test_that("a null that cannot avoid the set is reported as failing", {
    X <- small(n_cells = 300, n_genes = 900, seed = 23)
    cache <- rank_cache(X$matrix, X$genes, ceiling = 40)
    builder <- MatchedNullBuilder$new(cache, det_floor = 1e-4, seed = 1)
    big <- cache$genes[order(cache$detection, decreasing = TRUE)][1:400]
    built <- construct_expression_matched_null(cache, big, n_sets = 3, seed = 1)
    expect_gt(built$max_overlap, 0)
    expect_equal(built$status, "FAIL")
})

test_that("the adaptive floor does not censor the sparsest sets", {
    X <- small(n_cells = 300, n_genes = 900, seed = 24)
    cache <- rank_cache(X$matrix, X$genes, ceiling = 40)
    sparse <- cache$genes[order(cache$detection)][1:12]
    adaptive <- adaptive_detection_floor(cache, sparse, cap = 0.01)
    expect_lt(adaptive, 0.01)
    fixed <- construct_expression_matched_null(
        cache, sparse, n_sets = 4, seed = 3,
        tolerance = 0.05)
    expect_true(fixed$det_floor <= 0.01)
})

# ----------------------------------------------------------------------
# diagnostics and the checklist
# ----------------------------------------------------------------------
test_that("the sparsity report prefers the exact criterion when depth is known", {
    X <- small(n_cells = 250, n_genes = 800, seed = 31)
    cache <- rank_cache(X$matrix, X$genes, ceiling = 40)
    rep <- sparsity_report(cache, cache$genes[1:10])
    expect_equal(rep$criterion, "tie_break_share")
    expect_true(rep$tie_break_share >= 0 && rep$tie_break_share <= 1)
    expect_true(rep$frac_above_floor >= 0 && rep$frac_above_floor <= 1)
})

test_that("the verdict says which criterion it used", {
    X <- small(n_cells = 250, n_genes = 800, seed = 32)
    cache <- rank_cache(X$matrix, X$genes, ceiling = 40)
    v <- verdict(sparsity_report(cache, cache$genes[1:10]))
    expect_equal(v$criterion, "tie_break_share")
    expect_true(v$verdict %in% c("INTERPRETABLE",
                                 "INTERPRETABLE_WITH_MATCHED_NULL",
                                 "NOT_IDENTIFIABLE"))
})

test_that("a weak reason never lowers a severity a strong one has set", {
    # Every field that can raise the severity to HIGH, followed by every field
    # that would otherwise set it to MODERATE.  Comparing the three severities
    # as strings gets this wrong, because "MODERATE" sorts above "HIGH".
    high_share <- list(observed_zero_rate = 0.05, zero_rate_excess = 0.01,
                       tie_break_share = 0.9, frac_above_floor = 1,
                       detection_floor = 0.005)
    high_zero <- list(observed_zero_rate = 0.75, zero_rate_excess = 0.01,
                      tie_break_share = 0.01, frac_above_floor = 1,
                      detection_floor = 0.005)
    for (rep in list(high_share, high_zero)) {
        for (extra in list(list(), list(used_matched_null = FALSE),
                           list(outcome_driven_cutpoint = TRUE),
                           list(externally_replicated = FALSE))) {
            args <- c(list(report = rep), extra)
            v <- do.call(verdict, args)
            expect_equal(v$severity, "HIGH", info = paste(names(extra), collapse = ","))
            expect_equal(v$verdict, "NOT_IDENTIFIABLE")
        }
    }
})

test_that("omitting the matched null cannot improve the verdict", {
    clean <- list(observed_zero_rate = 0.05, zero_rate_excess = 0.01,
                  tie_break_share = 0.01, frac_above_floor = 1,
                  detection_floor = 0.005)
    unmatched <- verdict(clean, used_matched_null = FALSE)
    matched <- verdict(clean, used_matched_null = TRUE)
    expect_equal(matched$verdict, "INTERPRETABLE")
    expect_equal(unmatched$verdict, "INTERPRETABLE_WITH_MATCHED_NULL")
    expect_true(match(unmatched$severity, SEVERITY_ORDER) >=
                match(matched$severity, SEVERITY_ORDER))
})

test_that("the checklist runs end to end and serialises", {
    X <- small(n_cells = 250, n_genes = 800, seed = 33)
    cache <- rank_cache(X$matrix, X$genes, ceiling = 40)
    set.seed(9)
    axis <- rnorm(nrow(X$matrix))
    out <- diagnostic_checklist(cache, cache$genes[1:10], axis = axis,
                                cutpoint_method = "median",
                                config = list(n_null = 10,
                                              cutpoint_permutations = 25),
                                label = "demo")
    expect_equal(out$label, "demo")
    for (step in c("step1_sparsity", "step2_null_construction",
                   "step3_false_positive_rate", "step4_external_replication")) {
        expect_true(!is.null(out[[step]]), info = step)
    }
    expect_true(out$overall_verdict %in% c("INTERPRETABLE",
                                           "INTERPRETABLE_WITH_MATCHED_NULL",
                                           "NOT_IDENTIFIABLE"))
    expect_equal(out$step1_sparsity$criterion, "tie_break_share")

    path <- tempfile(fileext = ".json")
    to_json(out, path)
    back <- jsonlite::fromJSON(path, simplifyVector = FALSE)
    expect_equal(back$overall_verdict, out$overall_verdict)
})

test_that("collection fields serialise as arrays whatever their length", {
    # The Python implementation writes them as arrays, so a length-one reason
    # has to arrive as ["..."] rather than "..." or the two objects are not
    # interchangeable once parsed.  The field is written by hand here because
    # the point is the shape, not the values.
    for (reason in list("one reason", c("first", "second", "third"),
                        character(0))) {
        path <- tempfile(fileext = ".json")
        to_json(list(overall_verdict = "NOT_IDENTIFIABLE", reasons = reason,
                     step1_sparsity = list(status = "PASS"),
                     step4_external_replication = list(success = NULL)),
                path)
        txt <- paste(readLines(path), collapse = " ")
        expect_match(txt, '"reasons" *: *\\[', info = length(reason))
        back <- jsonlite::fromJSON(path, simplifyVector = FALSE)
        expect_length(back$reasons, length(reason))
        expect_true(is.list(back$reasons))
        # A null field is a value, not a collection, and stays null; deleting
        # one must not renumber the fields around it.
        expect_null(back$step4_external_replication$success)
        expect_equal(names(back$step4_external_replication), "success")
    }
    # A null inside a step record must not swallow the fields after it.
    path <- tempfile(fileext = ".json")
    to_json(list(step4 = list(attempted = TRUE, success = NULL, status = "PASS")),
            path)
    back <- jsonlite::fromJSON(path, simplifyVector = FALSE)
    expect_equal(names(back$step4), c("attempted", "success", "status"))
})

test_that("a one-gene null set is still an array of genes", {
    path <- tempfile(fileext = ".json")
    to_json(list(null_genes = list("CD8A", c("GZMB", "PRF1"))), path)
    back <- jsonlite::fromJSON(path, simplifyVector = FALSE)
    expect_length(back$null_genes, 2)
    expect_length(back$null_genes[[1]], 1)
    expect_equal(back$null_genes[[1]][[1]], "CD8A")
})

test_that("step 3 measures the rule and step 4 reports what it was told", {
    X <- small(n_cells = 250, n_genes = 800, seed = 34)
    cache <- rank_cache(X$matrix, X$genes, ceiling = 40)
    set.seed(10)
    axis <- rnorm(nrow(X$matrix))
    out <- diagnostic_checklist(cache, cache$genes[1:10], axis = axis,
                                cutpoint_method = "optimum",
                                externally_replicated = FALSE,
                                config = list(n_null = 10,
                                              cutpoint_permutations = 25))
    expect_true(out$step3_false_positive_rate$attempted)
    expect_equal(out$step3_false_positive_rate$method, "optimum")
    expect_equal(out$step4_external_replication$status, "FAIL")
    # an outcome-chosen cutpoint is a high-severity finding on its own
    expect_equal(out$severity, "HIGH")
})

test_that("no axis means steps 3 and 4 are reported as not attempted", {
    X <- small(n_cells = 200, n_genes = 700, seed = 35)
    cache <- rank_cache(X$matrix, X$genes, ceiling = 40)
    out <- diagnostic_checklist(cache, cache$genes[1:10],
                                config = list(n_null = 10))
    expect_false(out$step3_false_positive_rate$attempted)
    expect_equal(out$step4_external_replication$status, "NOT_ATTEMPTED")
})

test_that("an unknown configuration key is refused rather than ignored", {
    X <- small(n_cells = 150, n_genes = 600, seed = 36)
    cache <- rank_cache(X$matrix, X$genes, ceiling = 40)
    expect_error(diagnostic_checklist(cache, cache$genes[1:8],
                                      config = list(not_a_key = 1)),
                 "unknown configuration keys")
})

# ----------------------------------------------------------------------
# the conventional tests
# ----------------------------------------------------------------------
test_that("the outcome-chosen cutpoint costs more false positives than the median", {
    set.seed(12)
    score <- rnorm(400)
    outcome <- score > 0            # unrelated to the score's ranking by cut
    med <- cutpoint_fpr(score, outcome, n_perm = 200, method = "median", seed = 1)
    opt <- cutpoint_fpr(score, outcome, n_perm = 200, method = "optimum", seed = 1)
    expect_lt(med$fpr, 0.15)
    expect_gt(opt$fpr, med$fpr)
})

test_that("the permutation test is calibrated on unrelated vectors", {
    set.seed(13)
    score <- rnorm(200)
    axis <- rnorm(200)
    out <- all_conventional(score, axis, n_perm = 200, seed = 2)
    expect_true(out$permutation_p >= 0 && out$permutation_p <= 1)
    expect_true(is.finite(out$naive_p))
})

test_that("the Monte-Carlo P value defaults to two-sided", {
    # The tail is the one argument a caller forgets, and a one-sided default
    # answers a narrower question than the caller asked.  It did: the matched
    # nulls were read in the lower tail while the conventional analyses they are
    # compared against reject in either direction, which halved every matched
    # rejection rate and reported the matched null's power as zero.
    nulls <- seq(-1, 1, length.out = 201)
    centre <- stats::median(nulls)
    expect_equal(empirical_p(nulls, 0.5),
                 empirical_p(nulls, 0.5, tail = "two-sided"))
    expect_equal(null_summary(nulls, 0.5)$p_value,
                 empirical_p(nulls, 0.5, tail = "two-sided"))

    # Definition: distance from the null's own centre, not from zero.
    for (observed in c(-0.9, -0.2, 0, 0.4, 1)) {
        k <- sum(abs(nulls - centre) >= abs(observed - centre))
        expect_equal(empirical_p(nulls, observed, tail = "two-sided"),
                     (k + 1) / (length(nulls) + 1))
    }

    # A centred null makes the two conventions agree, which is why folding the
    # values about zero looks harmless; an off-centre one -- what imperfect
    # matching produces -- makes them differ, and the folded version then
    # answers the naive question the matched null was drawn to replace.
    expect_equal(empirical_p(abs(nulls), 0.5, tail = "upper"),
                 empirical_p(nulls, 0.5, tail = "two-sided"))
    shifted <- nulls + 0.4
    expect_lt(empirical_p(abs(shifted), 0.9, tail = "upper"),
              empirical_p(shifted, 0.9, tail = "two-sided"))
})

test_that("a family that was not drawn has no verdict", {
    # `kinds` is a free parameter, and the headline verdicts follow it.  Asking
    # for the expression family alone used to report `passed_strictest = FALSE`
    # -- a failed co-detection test that was never run -- and asking for
    # co-detection without a detection matrix was downgraded to the same FALSE.
    # The Python port raises in the second case, so the two ports disagreed
    # about what had happened on the same input.
    X <- small(n_cells = 250, n_genes = 700, seed = 41)
    cache <- rank_cache(X$matrix, X$genes, ceiling = 35)
    builder <- MatchedNullBuilder$new(cache, det_floor = 0.005, seed = 5)
    gs <- cache$genes[seq_len(8)]
    score <- aucell(cache, gs, max_rank = 35)
    axis <- score + seq(0, 1, length.out = length(score))

    partial <- tier2_internal(score, axis, builder, gs, 35, n_null = 8,
                              seed = 3, kinds = "expression")
    expect_equal(partial$passed_family, "expression")
    expect_true(is.logical(partial$passed))
    expect_true(is.na(partial$passed_strictest))
    expect_true(is.na(partial$passed_strictest_family))

    # Asked for and undrawable: refused in the words the Python port uses.
    expect_error(tier2_internal(score, axis, builder, gs, 35, n_null = 5,
                                seed = 3),
                 "needs detection_matrix")
})

# ----------------------------------------------------------------------
# cross-language equivalence
# ----------------------------------------------------------------------

read_fixture_matrix <- function(path) {
    lines <- readLines(path)
    header <- lines[1]
    n_cells <- as.integer(sub(".*n_cells=([0-9]+).*", "\\1", header))
    n_genes <- as.integer(sub(".*n_genes=([0-9]+).*", "\\1", header))
    # Lines 1 and 2 are the comment and the column names, so the text handed to
    # read.csv has no header of its own.
    triples <- utils::read.csv(text = paste(lines[-c(1, 2)], collapse = "\n"),
                               header = FALSE,
                               col.names = c("row", "col", "value"))
    X <- Matrix::sparseMatrix(i = triples$row + 1L, j = triples$col + 1L,
                              x = triples$value, dims = c(n_cells, n_genes),
                              repr = "C")
    list(matrix = X, genes = sprintf("G%05d", seq_len(n_genes) - 1L))
}

test_that("aucell reproduces the Python reference on the same matrix", {
    # A port has to reproduce the reference engine's numbers, not merely produce
    # numbers of the same kind.  The matrix and the Python scores are written by
    # tests/testthat/make_fixtures.py.
    ref <- readLines(fixture("aucell_reference.csv"))
    header <- ref[1]
    ceiling <- as.integer(sub(".*ceiling=([0-9]+).*", "\\1", header))
    max_rank <- as.integer(sub(".*max_rank=([0-9]+).*", "\\1", header))
    gene_set <- strsplit(sub(".*gene_set=([^ ]+).*", "\\1", header), ",")[[1]]
    expected <- utils::read.csv(text = paste(ref[-1], collapse = "\n"))

    dat <- read_fixture_matrix(fixture("matrix.csv"))
    cache <- rank_cache(dat$matrix, dat$genes, ceiling = ceiling, seed = 2024,
                        chunk = 100)
    got <- aucell(cache, gene_set, max_rank = max_rank)

    expect_equal(length(got), nrow(expected))
    # Exact to floating point: the tie-break seed and the ranking rule are the
    # same on both sides, so anything larger than rounding is a real difference.
    expect_lt(max(abs(got - expected$aucell)), 1e-9)
})

test_that("ucell reproduces the Python reference on the same matrix", {
    ref <- readLines(fixture("aucell_reference.csv"))
    ceiling <- as.integer(sub(".*ceiling=([0-9]+).*", "\\1", ref[1]))
    gene_set <- strsplit(sub(".*gene_set=([^ ]+).*", "\\1", ref[1]), ",")[[1]]
    expected <- utils::read.csv(text = paste(ref[-1], collapse = "\n"))
    r_max <- as.integer(round(median(Matrix::rowSums(
        read_fixture_matrix(fixture("matrix.csv"))$matrix > 0))))

    dat <- read_fixture_matrix(fixture("matrix.csv"))
    cache <- rank_cache(dat$matrix, dat$genes, ceiling = ceiling, seed = 2024,
                        chunk = 100)
    got <- ucell(cache, gene_set, r_max = min(r_max, ceiling))
    expect_lt(max(abs(got - expected$ucell)), 1e-9)
})

test_that("the diagnostics reproduce the Python reference", {
    ref <- utils::read.csv(fixture("diagnostics_reference.csv"))
    want <- stats::setNames(ref$value, ref$quantity)
    dat <- read_fixture_matrix(fixture("matrix.csv"))
    gene_set <- sprintf("G%05d", 0:11)
    cache <- rank_cache(dat$matrix, dat$genes, ceiling = 60, seed = 2024,
                        chunk = 100)
    rep <- sparsity_report(cache, gene_set)

    expect_equal(rep$observed_zero_rate, want[["observed_zero_rate"]],
                 tolerance = 1e-9)
    expect_equal(rep$structural_zero_rate, want[["structural_zero_rate"]],
                 tolerance = 1e-9)
    expect_equal(rep$mean_detection, want[["mean_detection"]], tolerance = 1e-9)
    expect_equal(rep$median_depth, want[["median_depth"]], tolerance = 1e-9)
    # The headline diagnostic, to six figures.
    expect_equal(rep$tie_break_share, want[["tie_break_share"]],
                 tolerance = 1e-8)
    expect_equal(rep$mean_inclusion, want[["mean_inclusion"]], tolerance = 1e-8)
})

test_that("comparability flags panels that place a set on different scales", {
    tab <- comparability_report(list(a = c(20000, 5000), b = c(24646, 4000)),
                                rank_frac = 0.05)
    expect_equal(nrow(tab), 2)
    expect_gt(attr(tab, "max_rank_ratio"), 1.2)
    expect_false(attr(tab, "scale_comparable"))
})

test_that("depth_report recommends an r_max from the data, not the default", {
    X <- small(n_cells = 200, n_genes = 800, seed = 41)
    dr <- depth_report(X$matrix)
    expect_equal(dr$n_genes_in_matrix, 800L)
    expect_gt(dr$ucell_r_max_implied, 0)
    expect_false(dr$ucell_default_is_appropriate)
})

# ----------------------------------------------------------------------
# the tie-break
# ----------------------------------------------------------------------
# These are the tests that would have failed against a generator-driven tie
# break, and they are the reason R/tiebreak.R exists: a draw from the stream
# depends on how the matrix was blocked and on which language is drawing, and
# neither dependence is acceptable in a port whose numbers are published.

test_that("the cache does not depend on how the work was blocked", {
    X <- small(n_cells = 120)
    a <- rank_cache(X$matrix, X$genes, ceiling = 25, seed = 3, chunk = 120)
    b <- rank_cache(X$matrix, X$genes, ceiling = 25, seed = 3, chunk = 37)
    c_ <- rank_cache(X$matrix, X$genes, ceiling = 25, seed = 3, chunk = 1)
    expect_identical(a$clipped, b$clipped)
    expect_identical(a$clipped, c_$clipped)
    # and the seed still changes the answer, so the equality above is not the
    # equality of a cache that ignores its seed
    d <- rank_cache(X$matrix, X$genes, ceiling = 25, seed = 4, chunk = 120)
    expect_false(identical(a$clipped, d$clipped))
})

test_that("a key is a function of the coordinates, not of their order", {
    whole <- sparseGenSetCal:::tie_break_keys(0:9, 50, seed = 7)
    band <- sparseGenSetCal:::tie_break_keys(2:4, 50, seed = 7)
    expect_equal(whole[3:5, ], band)
    expect_equal(dim(whole), c(10L, 50L))
    # in range, and spread over it rather than clustered
    expect_true(all(whole >= 0 & whole < 4294967296))
    expect_gt(length(unique(as.vector(whole))), 400)
})

test_that("an exact tie is settled by the key and not by the gene order", {
    # Two genes at the same count, and only room for one inside the ceiling.
    block <- matrix(c(5, 5, 0, 0), nrow = 1L)
    keys <- matrix(c(11, 2, 0, 0), nrow = 1L)
    expect_equal(sparseGenSetCal:::ranked_columns(block, keys, 1L)[1, 1], 2L)
    keys <- matrix(c(2, 11, 0, 0), nrow = 1L)
    expect_equal(sparseGenSetCal:::ranked_columns(block, keys, 1L)[1, 1], 1L)
})

test_that("an undetected gene never outranks a detected one", {
    # A count of one beats a zero whatever the keys say; this is the reason the
    # undetected fill lands beyond the ceiling in the first place.
    block <- matrix(c(1, 0, 1, 0), nrow = 2L, byrow = TRUE)
    keys <- matrix(c(4294967295, 0, 4294967295, 0), nrow = 2L, byrow = TRUE)
    expect_equal(sparseGenSetCal:::ranked_columns(block, keys, 1L)[, 1],
                 c(1L, 1L))
})

test_that("the tie-break keys reproduce the Python reference exactly", {
    # Not statistically similar: equal.  The keys are 32-bit integers computed
    # in 16-bit halves precisely so that both languages get the same ones.
    lines <- readLines(fixture("keys_reference.csv"))
    n_genes <- as.integer(sub(".*n_genes=([0-9]+).*", "\\1", lines[1]))
    seed <- as.integer(sub(".*seed=([0-9]+).*", "\\1", lines[1]))
    want <- utils::read.csv(text = paste(lines[-1], collapse = "\n"))
    cells <- sort(unique(want$cell))
    genes <- sort(unique(want$gene))
    K <- sparseGenSetCal:::tie_break_keys(cells, n_genes, seed = seed)
    got <- K[cbind(match(want$cell, cells), match(want$gene, genes))]
    expect_equal(got, as.numeric(want$key))
})

test_that("the ranking reproduces the Python reference cell by cell", {
    # The end-to-end check: not the hash on its own but the order it produced,
    # for every rank of every probed cell.
    lines <- readLines(fixture("ranks_reference.csv"))
    header <- lines[1]
    n_cells <- as.integer(sub(".*n_cells=([0-9]+).*", "\\1", header))
    n_genes <- as.integer(sub(".*n_genes=([0-9]+).*", "\\1", header))
    ceiling <- as.integer(sub(".*ceiling=([0-9]+).*", "\\1", header))
    seed <- as.integer(sub(".*seed=([0-9]+).*", "\\1", header))
    want <- utils::read.csv(text = paste(lines[-1], collapse = "\n"))

    dat <- read_fixture_matrix(fixture("matrix.csv"))
    # Deliberately a different chunk from the one Python used, so a difference
    # in blocking shows up as a failed test rather than as a lucky pass.
    cache <- rank_cache(dat$matrix, dat$genes, ceiling = ceiling, seed = seed,
                        chunk = 53)
    top <- sparseGenSetCal:::ranked_columns(
        as.matrix(dat$matrix),
        sparseGenSetCal:::tie_break_keys(seq_len(n_cells) - 1L, n_genes,
                                         seed = seed),
        ceiling)
    got <- top[cbind(match(want$cell, seq_len(n_cells) - 1L), want$rank)]
    expect_equal(got, want$gene + 1L)

    # and the same order read out of the package's own cache, so the test
    # covers rank_cache() and not only ranked_columns()
    for (cell in sort(unique(want$cell))) {
        row <- want[want$cell == cell, ]
        ranks <- cache$clipped[cell + 1L, ]
        hit <- which(ranks > 0)
        expect_equal(as.integer(ranks[hit][order(ranks[hit])]), sort(row$rank))
        expect_equal(hit[order(ranks[hit])], row$gene[order(row$rank)] + 1L)
    }
})

# ----------------------------------------------------------------------
# the edge cases the brief asks the framework to refuse or warn on
# ----------------------------------------------------------------------
# The framework's records arrive as `sparsegs_event` conditions, so they can be
# caught by class without silencing the caller's own warnings -- which is the
# reason the records are signalled rather than printed.
record_of <- function(expr) {
    tryCatch(expr, sparsegs_event = function(w) conditionMessage(w))
}

test_that("a score with no spread is refused", {
    # Edge case three: a set that is off in every cell, or on in every cell.
    # The correlation such a score enters is 0/0, and left alone it returns a
    # NaN that surfaces much later with nothing to say about which set produced
    # it -- so the refusal happens where the score is made, and names the set.
    check_score <- sparseGenSetCal:::check_score
    # The refusal is a record as well as an error, so a log of a failed run says
    # which set had no spread rather than only that some set did.
    seen <- character(0)
    quiet <- function(expr) withCallingHandlers(
        suppressWarnings(expr), message = function(m) {
            seen <<- c(seen, conditionMessage(m))
            invokeRestart("muffleMessage")
        })
    expect_error(quiet(check_score(rep(0.3, 50), label = "flat")),
                 "zero variance")
    # The advice the brief asks for is in the message, not only in the log: a
    # caller who catches the error is the one who has to act on it.
    expect_error(quiet(check_score(rep(0, 50), label = "all zero")),
                 "consider different genes")
    expect_length(seen, 2)
    expect_match(seen[1], "score_has_no_variance", fixed = TRUE)
    expect_match(seen[1], "label=flat", fixed = TRUE)
    # A label with a space in it is quoted, so the record parses back into the
    # fields it was built from.
    expect_match(seen[2], 'label="all zero"', fixed = TRUE)
    # A score with any real spread passes, and the check returns what it saw.
    expect_gt(check_score(seq(0, 1, length.out = 50)), MIN_SCORE_SD)
})

test_that("a perfect AUC warns with the three things to check", {
    # Edge case two: an AUC of 0.99 is a claim about the data, not the score.
    # It is warned about rather than refused, because a marker can genuinely
    # separate what it marks; the brief's three candidate explanations are
    # carried into the record so the warning can be acted on.
    check_auc <- sparseGenSetCal:::check_auc
    expect_silent(check_auc(0.5))
    record <- record_of(check_auc(0.999, label = "T-cell set"))
    expect_match(record, "suspicious_score_separation")
    expect_match(record, "T-cell set", fixed = TRUE)
    for (check in c("batch_effects", "outcome_leakage_into_cell_type_annotation",
                    "extreme_sparsity")) {
        expect_match(record, check, fixed = TRUE)
    }
    # The threshold travels with the record, so a reader of the log can tell how
    # far past it the value was without knowing this package's constants.
    expect_match(record, "threshold=0.99", fixed = TRUE)
    # A score that separates the two groups just as perfectly in the other
    # direction is the same confound, and auroc() does not fold its argument
    # about 0.5 -- so an upper-tail-only check would have missed half the ways
    # this case can arise.
    reversed <- record_of(check_auc(0.002, label = "T-cell set"))
    expect_match(reversed, "auc=0.002", fixed = TRUE)
    expect_match(reversed, "separation=0.998", fixed = TRUE)
})

test_that("a background too thin to draw from is refused not approximated", {
    # Edge case one, at the point the ladder gives up.  A query covering all but
    # a handful of the background leaves almost nothing to replace it with.  The
    # framework loosens the detection floor once, by the brief's ten per cent,
    # announces that it did, and -- if the pool is still too thin -- refuses.
    # Drawing from five genes and calling the result a matched null is the
    # failure this case exists to prevent.
    X <- small(n_cells = 200, n_genes = 600, seed = 41)
    cache <- rank_cache(X$matrix, X$genes, ceiling = 30)
    query <- utils::head(cache$genes, length(cache$genes) - 5)
    seen <- character(0)
    err <- tryCatch(
        withCallingHandlers(
            construct_expression_matched_null(cache, query, n_sets = 1, seed = 1),
            sparsegs_event = function(w) {
                seen <<- c(seen, conditionMessage(w))
                invokeRestart("muffleWarning")
            }),
        error = function(e) conditionMessage(e))
    expect_match(err, "Cannot construct matched null", fixed = TRUE)
    expect_match(err, "Consider different gene set", fixed = TRUE)
    # The loosening is announced before the refusal, so a log of a failed call
    # records that the framework tried the brief's remedy rather than skipping
    # straight to the error.
    record <- paste(seen, collapse = "\n")
    expect_match(record, "background_insufficient", fixed = TRUE)
    expect_match(record, "loosening", fixed = TRUE)
    expect_match(record, "loosened_to=", fixed = TRUE)
})

test_that("a gene set that fits its background is not warned about", {
    # The guard above has to stay quiet when there is no problem: a warning that
    # fires on ordinary input is a warning that gets filtered out of the log,
    # which costs the warnings that matter.  The widening has to be visible in
    # the object as well as the log, because a reader of a calibration record
    # cannot tell a matched null from a widened one by looking at the P value it
    # produced.
    X <- small(n_cells = 200, n_genes = 600, seed = 42)
    cache <- rank_cache(X$matrix, X$genes, ceiling = 30)
    query <- utils::head(cache$genes, max(20, length(cache$genes) %/% 10))
    seen <- character(0)
    built <- withCallingHandlers(
        construct_expression_matched_null(cache, query, n_sets = 1, seed = 1),
        sparsegs_event = function(w) {
            seen <<- c(seen, conditionMessage(w))
            invokeRestart("muffleWarning")
        })
    expect_length(seen, 0)
    expect_false(built$det_floor_loosened)
    expect_gt(built$n_available_background, MIN_BACKGROUND_GENES)
    expect_equal(built$pool_floor, built$det_floor)
})

test_that("the log is machine readable", {
    # Every field is `key=value`, so a log can be counted and not just read.
    # The point of emitting records rather than sentences is that the question
    # "how often did this happen" has an answer, and that answer requires the
    # format to hold.
    line <- record_of(sparseGenSetCal:::event(
        "warning", "test_event", count = 3, ratio = 0.125, ok = TRUE,
        name = "a value with spaces", absent = NULL))
    fields <- regmatches(
        line, gregexpr("(\\w+)=(\"[^\"]*\"|\\S+)", line))[[1]]
    got <- setNames(sub("^\\w+=", "", fields), sub("=.*$", "", fields))
    expect_equal(unname(got[["count"]]), "3")
    expect_equal(unname(got[["ratio"]]), "0.125")
    expect_equal(unname(got[["ok"]]), "true")
    expect_equal(unname(got[["name"]]), "\"a value with spaces\"")
    expect_false("absent" %in% names(got))
})

test_that("an unknown log level is refused rather than guessed at", {
    # A caller who asked for "warn" and was silently given "warning" cannot
    # tell the difference between a level that was accepted and one that was
    # guessed at.
    expect_error(set_log_level("warn"), "unknown log level")
    expect_equal(set_log_level("error"), "error")
    set_log_level("warning")
})

# ----------------------------------------------------------------------
# the axis's own confound with depth, folded into the verdict
# ----------------------------------------------------------------------
test_that("the axis confound qualifies a verdict without refusing it", {
    # A matched null is calibrated *under* this confound: the replacement sets
    # come from a matrix with the same depth distribution and carry the same
    # tie-break behaviour, so the null distribution moves with the observed
    # statistic and the confound is priced in.  Calling a depth-confounded axis
    # NOT_IDENTIFIABLE outright would say the framework's own recommended
    # analysis cannot be trusted on the data it was built for.
    clean <- list(observed_zero_rate = 0.05, zero_rate_excess = 0.01,
                  tie_break_share = 0.01, frac_above_floor = 1.0,
                  detection_floor = 0.005)

    clear <- verdict(clean, used_matched_null = TRUE,
                     preflight = list(verdict = "CLEAR"))
    expect_equal(clear$verdict, "INTERPRETABLE")
    expect_equal(clear$severity, "LOW")

    for (name in c("CAUTION", "CONFOUNDED")) {
        v <- verdict(clean, used_matched_null = TRUE,
                     preflight = list(verdict = name))
        expect_equal(v$verdict, "INTERPRETABLE", info = name)
        expect_equal(v$severity, "MODERATE", info = name)
        expect_true(any(grepl("sequencing depth", v$reasons)), info = name)
    }

    # Without a matched null the confound joins the reasons already there, and
    # the verdict is the one that says a matched null is owed.
    v <- verdict(clean, used_matched_null = FALSE,
                 preflight = list(verdict = "CONFOUNDED"))
    expect_equal(v$verdict, "INTERPRETABLE_WITH_MATCHED_NULL")
    expect_true(any(grepl("expression-matched null", v$reasons)))
    expect_true(any(grepl("sequencing depth", v$reasons)))

    # A verdict that already refuses is not softened by the extra reason: the
    # heavier severity still wins, which is what comparing the names as strings
    # gets wrong -- "MODERATE" sorts above "HIGH".
    v <- verdict(utils::modifyList(clean, list(observed_zero_rate = 0.7)),
                 used_matched_null = TRUE,
                 preflight = list(verdict = "CONFOUNDED"))
    expect_equal(v$verdict, "NOT_IDENTIFIABLE")
    expect_equal(v$severity, "HIGH")
})

test_that("the checklist reads the depth off the cache", {
    # The pre-flight has to run without being asked to.  The axis below is the
    # depth itself, so the correlation is -1 -- a positive test rather than a
    # borderline one, because the question is whether the number is computed at
    # all when no `depth` argument is passed.  The density is set so that the
    # median cell is comfortably below `max_rank`: `tau` is zero for every cell
    # at or above that ceiling, so a matrix deeper than it flattens the axis's
    # image into a constant and the correlation stops being near one.
    X <- make_synthetic_matrix(n_cells = 300, n_genes = 2000, density = 0.02,
                               seed = 51)
    cache <- rank_cache(X$matrix, X$genes, ceiling = 100)
    axis <- as.numeric(cache$depth)
    out <- diagnostic_checklist(cache, cache$genes[1:12], axis = axis,
                                used_matched_null = TRUE,
                                config = list(n_null = 3,
                                              cutpoint_permutations = 25))

    expect_false(is.null(out$preflight))
    expect_equal(out$preflight$verdict, "CONFOUNDED")
    expect_gt(abs(out$preflight$tau_axis_rho), 0.9)
    expect_true(any(grepl("sequencing depth", out$reasons)))
    # The band it judged against travels with the call, so a reader can see
    # which regime the dataset is in rather than taking the threshold on trust.
    expect_equal(out$preflight$chance_band, 1.96 / sqrt(out$n_cells - 3),
                 tolerance = 1e-12)

    # An axis that is not the depth is not warned about, so the reason above is
    # the correlation and not the fact that a pre-flight ran.
    set.seed(52)
    free <- diagnostic_checklist(cache, cache$genes[1:12],
                                 axis = rnorm(out$n_cells),
                                 used_matched_null = TRUE,
                                 config = list(n_null = 3,
                                               cutpoint_permutations = 25))
    expect_equal(free$preflight$verdict, "CLEAR")
    expect_false(any(grepl("sequencing depth", free$reasons)))
})

test_that("a tie-break that never varies is clear and says so", {
    # Every cell deeper than `max_rank` contributes tau = 0; on a matrix where
    # all of them are, tau is constant and its correlation with the axis does
    # not exist.  `cor.test` reports NA here with a warning about a zero
    # standard deviation, which `spearman` suppresses so that the degenerate
    # input is a number and not a diagnostic.  This is not an exotic input: it
    # is what a deep 10x matrix looks like whenever five per cent of the gene
    # panel falls below the median cell.
    depth <- rep(500, 300)
    axis <- seq(0, 1, length.out = 300)
    pre <- preflight(depth, axis, 100, 2000)
    expect_true(pre$tau_constant)
    expect_equal(pre$tau_sd, 0)
    expect_true(is.na(pre$tau_axis_rho))
    # Clear, and correctly so: a component that never varies cannot carry an
    # association with anything.
    expect_equal(pre$verdict, "CLEAR")

    # A matrix with depth variation still produces a correlation, so the branch
    # above is the degenerate case and not the ordinary one.
    live <- seq(20, 400, length.out = 300)
    expect_true(is.finite(preflight(live, axis, 100, 2000)$tau_axis_rho))
})
