"""Render ``docs/API.md`` from the package's own docstrings.

The documentation is generated rather than written so that it cannot drift away
from the code: a signature that changes here changes in the manual, and a
function that gains a parameter gains it in the manual.  Run it after any change
to the public surface and commit the result -- the file is a build artefact that
is checked in on purpose, so that a reader of the repository sees the API without
running anything.

    python docs/build_api.py

Every name in ``sparsegs.__all__`` is documented.  The order follows the module
list below rather than ``__all__``, because the modules are the reading order.
"""

from __future__ import annotations

import inspect
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PKG = os.path.dirname(HERE)
sys.path.insert(0, PKG)

import sparsegs  # noqa: E402

#: The reading order.  One entry per module: (module, one-line role).  The role
#: is the part a docstring does not carry -- why the module is there at all.
MODULES = [
    ("sparsegs.theory", "The arithmetic of the tie-break channel: equations "
                        "(1)-(3) and the quantities that follow from them."),
    ("sparsegs.rankcache", "Ranks every cell once and reuses them, which is "
                           "what makes a sweep over hundreds of gene sets "
                           "affordable."),
    ("sparsegs.tiebreak", "How a tie is settled, deterministically and "
                          "identically in both languages, instead of by a draw "
                          "from a generator."),
    ("sparsegs.scores", "The scoring functions under test, including the "
                        "AUCell top-block rule the tie-break arises from."),
    ("sparsegs.nulls", "The matched null families, with the detection floor "
                       "and the overlap accounting that make them nulls."),
    ("sparsegs.diagnostics", "The checklist's first two steps: how sparse the "
                             "set is, and what that costs."),
    ("sparsegs.stats", "Association, permutation and cutpoint machinery, "
                       "including the false-positive rate of each rule."),
    ("sparsegs.analyses", "The conventional analyses the framework is compared "
                          "against."),
    ("sparsegs.calibrate", "The assembled four-step checklist and the "
                           "calibration object it returns."),
    ("sparsegs.convenience", "The decision table and the fitted rejection "
                             "probability, as pure functions a caller can "
                             "run before any scoring."),
    ("sparsegs.tiers", "The three validation tiers: technical, internal, "
                       "external."),
    ("sparsegs.comparators", "Head-to-head scoring against other "
                             "implementations."),
    ("sparsegs.simulate", "The ground-truth simulator the operating "
                          "characteristics are measured on."),
    ("sparsegs.report", "The self-contained HTML report."),
    ("sparsegs.events", "Structured records rather than prose: one "
                        "``event field=value`` line per diagnostic, so a run "
                        "can be counted as well as read."),
]


def _signature(obj):
    try:
        return f"{obj.__name__}{inspect.signature(obj)}"
    except (TypeError, ValueError):          # pragma: no cover
        return obj.__name__


def _public(module):
    """Public callables and classes of ``module``, in definition order, and the
    module-level constants beside them.

    Constants are documented rather than skipped: the defaults in
    ``DEFAULT_CONFIG`` and ``DEFAULT_THRESHOLDS`` are the numbers every rate in
    the manuscript was produced with, so a reader needs them in the manual as
    much as they need the signatures.
    """
    names = getattr(module, "__all__", None)
    if names is None:
        names = [n for n in vars(module) if not n.startswith("_")]
    funcs, consts = [], []
    for name in names:
        obj = getattr(module, name, None)
        if obj is None or inspect.ismodule(obj):
            continue
        if inspect.isfunction(obj) or inspect.isclass(obj):
            if getattr(obj, "__module__", None) == module.__name__:
                funcs.append((name, obj))
        else:
            consts.append((name, obj))
    return funcs, consts


def _value(obj, limit=110):
    r = repr(obj)
    return r if len(r) <= limit else r[:limit] + " ..."


def _anchor(name):
    return "#" + name.lower().replace("_", "-")


def render():
    lines = [
        "# sparsegs API",
        "",
        "Generated by `docs/build_api.py` from the package docstrings.  Every "
        "name in `sparsegs.__all__` appears below; the order is the order a "
        "reader needs them in, not the alphabetical order.",
        "",
        "## Contents",
        "",
    ]
    for mod_name, role in MODULES:
        mod = __import__(mod_name, fromlist=["_"])
        lines.append(f"- [`{mod_name}`]({_anchor(mod_name)}) — {role}")
    lines += ["", "---", ""]

    for mod_name, role in MODULES:
        mod = __import__(mod_name, fromlist=["_"])
        lines += [f"## {mod_name}", "", role, ""]
        doc = inspect.getdoc(mod) or ""
        # The module docstring is the chapter; its own first line is the title
        # and is already in the contents, so it is not repeated.
        lines += [doc, ""] if doc else []
        funcs, consts = _public(mod)
        if consts:
            lines += ["### Constants", ""]
            for name, obj in consts:
                lines += [f"**`{name}`**", "", "```python",
                          f"{name} = {_value(obj)}", "```", ""]
                doc = inspect.getdoc(type(obj)) if not isinstance(
                    obj, (dict, list, tuple, str, int, float, bool)) else None
                if doc:
                    lines += [doc.split("\n")[0], ""]
                if isinstance(obj, dict):
                    lines += ["| key | value |", "| --- | --- |"]
                    for k in sorted(obj, key=str):
                        lines.append(f"| `{k}` | `{_value(obj[k], 40)}` |")
                    lines.append("")
        for name, obj in funcs:
            lines += [f"### {name}", "", "```python", _signature(obj), "```", ""]
            doc = inspect.getdoc(obj) or "(no docstring)"
            lines += [doc, ""]
            if inspect.isclass(obj):
                methods = [(n, o) for n, o in vars(obj).items()
                           if not n.startswith("_")
                           and (inspect.isfunction(o) or isinstance(o, property))]
                for n, o in methods:
                    title = n if not isinstance(o, property) else f"{n} (property)"
                    lines += [f"#### {title}", "", "```python",
                              _signature(o) if not isinstance(o, property)
                              else f"{n}  # property", "```", "",
                              inspect.getdoc(o) or "(no docstring)", ""]
        lines += ["---", ""]
    return "\n".join(lines).rstrip() + "\n"


def main():
    text = render()
    out = os.path.join(HERE, "API.md")
    with open(out, "w", encoding="utf-8") as fh:
        fh.write(text)
    n_modules = len(MODULES)
    n_entries = text.count("\n### ")
    print(f"wrote {out}: {n_modules} modules, {n_entries} documented names, "
          f"{len(text.splitlines())} lines")


if __name__ == "__main__":
    main()
